name = "ProbabilisticRoadMap"
uuid = "773847ca-07cc-414d-a27c-4458bbc76b2b"
authors = ["Himanshu Gupta"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
